---
- hosts: web
  become: true
  tasks:
    - name: Install required packages
      apt:
        name: [docker.io, docker-compose]
        state: present
        update_cache: true

    - name: Start Docker Compose services
      command: docker-compose up -d
      args:
        chdir: /home/ubuntu/simple-devops-stack/docker
