name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lint Ansible playbook
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible
          ansible-playbook --syntax-check ansible/playbook.yml
